wip: new 2auth reset password workflow
ArkEcosystem/laravel-fortify pull request #133
Opened 2021-04-20 20:51 UTC by alfonsobries

## Summary

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

2021-05-03 08:11 UTC, ItsANameToo commented on src/Http/Controllers/TwoFactorAuthenticatedPasswordResetController.php
> +     * @param string                        $oken
```suggestion
     * @param string                        $token
```

2021-05-03 09:48 UTC, ItsANameToo requested changes
@alfonsobries I was unable to reset the password with a recovery-code. Meanwhile that same recovery code (afterwards) worked fine for logging in.

2021-05-03 16:31 UTC, alfonsobries commented
@ItsANameToo should be working now

2021-05-04 10:32 UTC, ItsANameToo approved these changes

2021-05-04 10:32 UTC, merged