refactor: new digits length rule for 2FA setup
ArkEcosystem/laravel-fortify pull request #145
Opened 2021-06-15 09:49 UTC by Highjhacker

## Summary

https://app.clickup.com/t/hq4nng

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

2021-06-15 10:03 UTC, ItsANameToo requested changes

2021-06-15 10:03 UTC, ItsANameToo commented on src/Components/TwoFactorAuthenticationForm.php
> +            'state.otp' => ['required', new OneTimePassword($this->state['two_factor_secret']), 'digits_between:4,10'],
6, otp is always 6

2021-06-16 15:09 UTC, ItsANameToo commented
@Highjhacker have you tried installing this on MSQ?

2021-06-16 15:11 UTC, Highjhacker commented
Na, tried it by modifying the file within `vendor/` and tested it from there and also ran the tests on `laravel-ui` and was all green, I guess something is wrong ? :trollface:

2021-06-16 15:19 UTC, ItsANameToo requested changes
this doesn't seem to do much 🤔 and when you enable it it will simply say the code does not work, nothing regarding to being limited to 6
<img width="671" alt="image" src="https://user-images.githubusercontent.com/35610748/122246513-e245be00-cec6-11eb-820d-29bb077e1adc.png">

2021-06-16 15:57 UTC, ItsANameToo requested changes
- make the input field also take 6 digits max or people will still be able to fill in more than 6 digits as validation only hits when pressing the button
- above applies to all OTP fields, keep it consistent and limit them to 6 in the frontend already wherever they are used

2021-06-16 15:57 UTC, ItsANameToo commented on src/Components/TwoFactorAuthenticationForm.php
> +            'state.otp' => ['required', new OneTimePassword($this->state['two_factor_secret']), 'digits:6'],
switch order, `digits:6` before the `new OneTimePassword` rule

2021-06-16 18:29 UTC, Highjhacker commented
@ItsANameToo Applied the `max=6` on inputs but it doesn't seems to work at all 🤔 Also I don't think I can add much to the validation for the Login part, or at least haven't found how, checked a bit at `laravel-fortify` since most if from there but nothing.

2021-06-17 08:12 UTC, ItsANameToo commented
@Highjhacker because passing `max` sets `maxlength` and that doesn't work on number inputs. This needs to be refactored: https://github.com/ArkEcosystem/laravel-ui/blob/master/resources/views/inputs/includes/input-field.blade.php#L25 and was the plan for a while. I don't think anything uses that property anymore but you would have to recheck that. If it's used then document it so it can be updated when the UI lib gets updated on the respective project

2021-06-17 08:13 UTC, ItsANameToo commented
@Highjhacker sidenote, `max` will work for number inputs but that doesn't define the length but an actual number

2021-06-17 15:46 UTC, Highjhacker commented
@ItsANameToo Used pattern but it's not like it's effectively preventing user to input more than 6 numbers, think we would need some JS for that, want me to have a look or it's fine as it is ? 🤔

2021-06-17 15:51 UTC, ItsANameToo commented
nah if `max` doesn't cut it then so be it, backend only guard then

2021-06-18 13:43 UTC, ItsANameToo approved these changes

2021-06-22 08:37 UTC, ItsANameToo approved these changes

2021-06-22 08:38 UTC, merged