refactor: skip redirect to verification route if username is used instead of email
ArkEcosystem/laravel-fortify pull request #162
Opened 2021-07-15 10:19 UTC by Highjhacker

## Summary

Related to https://github.com/ArkEcosystem/nodem/pull/102, last issue I was facing was the following exception : 
`Symfony\Component\Routing\Exception\RouteNotFoundException Route [verification.notice] not defined.`

So, removing that redirect if we don't use the email at all, and redirect on the homepage instead, which fix my issue on Nodem. 

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

2021-07-15 13:23 UTC, leMaur approved these changes

2021-07-19 13:03 UTC, ItsANameToo approved these changes

2021-07-19 14:49 UTC, ItsANameToo requested changes
on second thought, wouldn't it make more sense to not enable this redirect at all when the `Features::emailVerification()` is not set in the fortify config? then the whole verification part should be disabled and the redirect shouldn't happen @Highjhacker

2021-07-19 15:22 UTC, Highjhacker commented
Something like that @ItsANameToo ? 🤔

2021-07-19 15:27 UTC, ItsANameToo commented
@Highjhacker more a general handling of that `RegisterReponse` as it does a check for an invite that will never trigger if you disable the invite settings. Can you check how fortify in itself handles this and what it does when someone disables the `Features::emailVerification(),` setting? I'd expect them to have some handling for that redirect too in that case

2021-07-19 15:37 UTC, Highjhacker commented
Will have a check tomorrow, leaving it here for reminder : 

https://laravel.com/docs/8.x/fortify#email-verification
https://github.com/laravel/fortify/blob/1.x/config/fortify.php#L18

2021-07-20 13:41 UTC, ItsANameToo commented
@Highjhacker can you update your branch with latest develop? So the test can be added for the change brian did

2021-07-20 13:42 UTC, closed without merging