fix: failing test and missing coverage for RegisterResponse
ArkEcosystem/laravel-fortify pull request #170
Opened 2021-07-20 15:35 UTC by Highjhacker

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

2021-07-20 21:09 UTC, alexbarnsley requested changes

2021-07-20 21:09 UTC, alexbarnsley commented on tests/Responses/RegisterResponseTest.php
> +        ->with('invitations.accept', $invitation)
need to fix indentation here

2021-07-20 21:10 UTC, alexbarnsley commented
only a minor thing but needs updating

2021-07-21 07:47 UTC, ItsANameToo approved these changes

2021-07-21 07:47 UTC, merged